/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_craftoriya_memory_optimisations_jni_AllocatedArrayJNI */

#ifndef _Included_net_craftoriya_memory_optimisations_jni_AllocatedArrayJNI
#define _Included_net_craftoriya_memory_optimisations_jni_AllocatedArrayJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_craftoriya_memory_optimisations_jni_AllocatedArrayJNI
 * Method:    allocate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_craftoriya_memory_1optimisations_jni_AllocatedArrayJNI_allocate
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_craftoriya_memory_optimisations_jni_AllocatedArrayJNI
 * Method:    deallocate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_craftoriya_memory_1optimisations_jni_AllocatedArrayJNI_deallocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_craftoriya_memory_optimisations_jni_AllocatedArrayJNI
 * Method:    write
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_net_craftoriya_memory_1optimisations_jni_AllocatedArrayJNI_write
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     net_craftoriya_memory_optimisations_jni_AllocatedArrayJNI
 * Method:    read
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_net_craftoriya_memory_1optimisations_jni_AllocatedArrayJNI_read
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     net_craftoriya_memory_optimisations_jni_AllocatedArrayJNI
 * Method:    copy
 * Signature: (JIJII)V
 */
JNIEXPORT void JNICALL Java_net_craftoriya_memory_1optimisations_jni_AllocatedArrayJNI_copy
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
